title: RCAAC
description: Ritchie County's All-American Celebration
baseurl: ""
url: "http://localhost:4000"

email: rcaac23@gmail.com

markdown: kramdown

plugins:
  - jekyll-admin
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
